# Generated by Django 4.2.8 on 2026-01-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_sessions', to='quiz_app.question'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('timed', 'Timed'), ('mock', 'Mock Test')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit in minutes, 0 = no limit'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='title',
            field=models.CharField(default='Quiz', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz'),
        ),
    ]
